name : Foundation5/github pages/Jykill starter
brand : My Project
description : This is the description of my project
keyword :
url : http://daigofuji.github.io/jekyll-foundation-6-starter/
email : infinitegarg@gmail.com
twitter : infinitegarg
github : infinitegarg
behance : infinitegarg
dribbble : infinitegarg
codepen : infinitegarg
linkedin : infinitegarg
angel : infinitegarg
author : Anant Garg
year : 2018
markdown : kramdown
exclude: ["node_modules", "gulpfile.js", "package.json"]

permalink: /:title
