name : Product Designer
brand : My Project
description : Anant Garg is a Product Designer at Innovaccer based in Noida, HQ in San Francisco. A Computer Science graduate who believes in creating user-centered experiences backed by strong business & development research.
keyword : Product Designer, UX Designer, Frontend Developer, Delhi, UI Designer, Healthcare
url : http://anantgarg.design
email : infinitegarg@gmail.com
twitter : infinitegarg
github : infinitegarg
behance : infinitegarg
dribbble : infinitegarg
codepen : infinitegarg
linkedin : infinitegarg
angel : infinitegarg
author : Anant Garg
year : 2018
markdown : kramdown
exclude: ["node_modules", "gulpfile.js", "package.json"]

permalink: /:title/
# relative_permalinks: false
